### ISSUE TITLE
PB with dvb-usb-dib0700-1.20.fw

### ISSUE THREAD

**Issue by tatoomi** [cernekee/linux-firmware#1]
Hello
since France has passed MP4, it will seem that the driver is no longer functional.
would it be possible to modify it?

  http://forum.ubuntu-fr.org/viewtopic.php?id=2005074

If you other information , contact me.

Thank you

**Comment by cernekee** [comment]
I think you may want to contact the upstream [linux-media](http://vger.kernel.org/vger-lists.html#linux-media) or [linux-firmware](https://www.kernel.org/doc/readme/firmware-README.AddingFirmware) lists. This repository is just a local fork that I used for a personal project a few years ago.
